# This is a basic workflow to showcase the use of Reusable Workflows
# dckr_pat_Qil3uZEu6B1PSjjea3FWEpRT7jw (docker token)

name: Reusable

on:
  workflow_dispatch:

jobs:
  do-it:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!
      - name: test
        run: |
          moi= $(curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: token ${{ secrets.REGISTRY_TOKEN }}"\
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/aristidejoudubois/ReusableWorkflow/actions/secrets)
          echo $moi

  docker:
    uses: aristidejoudubois/ReusableWorkflow/.github/workflows/build.yml@main
    with:
      image_name: my-awesome-app
      tag: $GITHUB_RUN_NUMBER
    secrets: inherit
      #registry_username: ${{ secrets.REGISTRY_USERNAME }}
      #registry_token: ${{ secrets.REGISTRY_TOKEN }}
