name: dep

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v3
      - name: use
        uses: aristidejoudubois/ReusableWorkflow/.github/actions/cache
